### ISSUE TITLE
"Create An Account" is not working 

### ISSUE THREAD

**Issue by purbanow** [greenhub-project/docs#1]
Hi,
I found out that the following link doesn't work:
https://greenhub.di.ubi.pt/register for creating an account which was provided here: 
https://docs.greenhubproject.org/api/getting-started.html#create-an-account

Extra note:
There is no email contact on the website which is sad :(

**Comment by hmatalonga** [comment]
Hello!

My apologies, the system has been undergoing a migration process and it took a long time to finish...

Thank you for contacting us. Every module of the project is being updated at the moment. The documentation will be updated accordingly as the updates are released...

The registration is now available again!
Please visit https://farmer.greenhubproject.org/register to create a new account

For the time being, opening a new issue is the easiest way to contact us and fix any potential problems.

For anything related with the web application, datasets or API, feel free to open an issue [here](https://github.com/greenhub-project/farmer/issues/new).

If you need any help, please let me know :wink:

**Comment by purbanow** [comment]
Hi @hmatalonga,

Thanks for very fast response. 

It's working so I'm going to close this Issue.
